/**
 * GET /api/reports/ttb/storage/[period]
 *
 * TTB Form 5110.11 — Report of Storage Operations.
 *
 * Generated by aggregating Transfer ledger entries whose source or destination
 * TTB account is `storage`. Reversed transfers are excluded.
 */
export default defineEventHandler(async (event) => {
	const period = event.context.params?.period;
	if (!period) {
		throw createError({ status: 400, statusText: 'Period is required' });
	}
	return await generateTTBReport('5110.11', period);
});
