/**
 * GET /api/reports/ttb/processing/[period]
 *
 * TTB Form 5110.28 — Report of Processing Operations.
 *
 * Generated by aggregating Transfer ledger entries whose source or destination
 * TTB account is `processing`. Reversed transfers are excluded.
 */
export default defineEventHandler(async (event) => {
	const period = event.context.params?.period;
	if (!period) {
		throw createError({ status: 400, statusText: 'Period is required' });
	}
	return await generateTTBReport('5110.28', period);
});
