/**
 * GET /api/reports/ttb/production/[period]
 *
 * TTB Form 5110.40 — Report of Production Operations.
 *
 * Generated by aggregating Transfer ledger entries whose source or destination
 * TTB account is `production`. Reversed transfers are excluded.
 *
 * 27 CFR §19.580–§19.583 (records).
 */
export default defineEventHandler(async (event) => {
	const period = event.context.params?.period;
	if (!period) {
		throw createError({ status: 400, statusText: 'Period is required' });
	}
	return await generateTTBReport('5110.40', period);
});
